language: node_js

node_js:
  - "stable"

cache:
  directories:
    - node_modules

install:
  - npm install
  - cd client && npm install

before_script:
  - npm run build
  - sleep 15
  - mongo mydb_test --eval 'db.createUser({user:"travis",pwd:"test",roles:["readWrite"]});'

script:
  - npm run test
  - npm run test:client
  - npm run client:build

on:
  branch: master

after_success:
  - npm run coverage

services:
  - mongodb
